# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af6cc42de595e875801e592c7c79ec6786f96f4363d75b6061d2c3698604503c34211c7f15eee7eb859aa62377029a1fe3cf8b71b7d8e47fffac7499103a9cf3

test:
  secret_key_base: 3ab163f2e4c92f360acc5eb19e56d4bd96b87136f07e55cd9458f2b75f725259e201331c4081598cd9e4645f3b01b8a106215771d4604ac9d78bed2e10834e63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
